spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bootuser
    password: bootuser
    url: jdbc:mysql://localhost:3306/bootex

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher